"""Gemini Explainer Service — Generates executive summaries of the debate.

Purpose:
    Uses Google's Gemini API to analyze the courtroom debate history
    and synthesize a cohesive executive summary (Judge Brief).

Dependencies:
    google.generativeai (optional)
"""

import os
import logging
from typing import Any

from models.proposal import Proposal
from engine.history import AuditHistory

try:
    import google.generativeai as genai
    HAS_GEMINI = True
except ImportError:
    HAS_GEMINI = False

logger = logging.getLogger(__name__)

def generate_judge_brief(history: AuditHistory, final_proposal: Proposal) -> str:
    """Generate a narrative summary of the debate using Gemini.

    Parameters
    ----------
    history : AuditHistory
        The full audit trail of the courtroom session.
    final_proposal : Proposal
        The current or final state of the neighborhood proposal.

    Returns
    -------
    str
        The narrative summary generated by Gemini.
    """
    if not HAS_GEMINI:
        return "Gemini API is unavailable. Please install `google-generativeai` to enable automated judge briefs."

    api_key = os.environ.get("GEMINI_API_KEY")
    if not api_key:
        return "Gemini API key not found. Please set the GEMINI_API_KEY environment variable."

    try:
        genai.configure(api_key=api_key)
        # Using a deterministic model as much as possible, though Gemini has inherent variance
        model = genai.GenerativeModel("gemini-2.5-flash")
        
        # Construct the prompt
        prompt = (
            "You are an executive summarizer for the 'Neighborhood Courtroom' AI simulation.\n"
            "Below is the raw audit history of a multi-agent debate regarding urban planning parameters.\n"
            "Please read the history and generate a concise, professional 'Judge Brief' (1-2 paragraphs).\n"
            "Focus on the main conflicts, which agents disagreed, and how the judge resolved them.\n"
            "Do not invent data; only summarize the provided history.\n\n"
            "## Final Proposal State\n"
            f"Housing Units: {final_proposal.housing_units}\n"
            f"Green Space: {final_proposal.green_space_pct}%\n"
            f"Parking Spaces: {final_proposal.parking_spaces}\n"
            f"Community Center Sqft: {final_proposal.community_center_sqft}\n\n"
            "## Audit History\n"
        )
        
        # We will dump all explain_parameter views into the prompt
        for param in ["housing_units", "green_space_pct", "parking_spaces", "community_center_sqft"]:
            explanation = history.explain_parameter(param)
            if "Unresolved or unknown" not in explanation:
                prompt += f"### Parameter: {param}\n{explanation}\n\n"
        
        response = model.generate_content(prompt)
        return response.text.strip()
    except Exception as e:
        logger.error(f"Gemini API generation failed: {e}")
        return f"Failed to generate brief. Reason: {e}"
