"""Gemini Explainer Service — Generates executive summaries of the debate.

Purpose:
    Uses Google's Gemini API to analyze the courtroom debate history
    and synthesize a cohesive executive summary (Judge Brief).

Dependencies:
    google.generativeai (optional)
"""

import os
import logging
from typing import Any

from models.proposal import Proposal
from engine.history import AuditHistory
from engine.session import CourtroomSession
from llm.provider_factory import get_provider
from llm.base import LLMAuthError, LLMProviderError
from llm.budget import is_budget_exhausted

logger = logging.getLogger(__name__)

def build_audit_from_session(session: CourtroomSession) -> AuditHistory:
    audit = AuditHistory()
    for rnd in session.debate_rounds:
        for agent_name, output in rnd.agent_outputs.items():
            for param, val in output.proposed_changes.items():
                audit.record_decision(rnd.round_number, agent_name, param, val)
        for conflict in rnd.detected_conflicts:
            audit.record_conflict(rnd.round_number, conflict)
            if conflict.disagreement_severity == "high":
                audit.record_resolution(rnd.round_number, conflict.parameter, "human review required")
            else:
                audit.record_resolution(rnd.round_number, conflict.parameter, "auto-resolved", getattr(rnd.closing_state, conflict.parameter))
    for ov in session.override_history:
        audit.record_override(ov["round_number"], ov["parameter"], ov["value"])
    return audit

def generate_judge_brief_fallback(session: CourtroomSession) -> str:
    """Generate a deterministic fallback summary of the debate when LLM is unavailable."""
    from engine.summary import generate_plain_language_summary
    
    from tools.cost_calculator import CostCalculator
    from tools.data_loader import DataLoader
    summary = generate_plain_language_summary(session, CostCalculator(DataLoader()))
    
    # Extract standards flags from the final round
    flags_text = ""
    if session.debate_rounds:
        last_round = session.debate_rounds[-1]
        all_flags = []
        
        # Check round 3, 2, 1 opinions for flags
        for agent_name in ["climate", "finance", "community"]:
            opinion = None
            if hasattr(last_round, "round_3_opinions") and agent_name in last_round.round_3_opinions:
                opinion = last_round.round_3_opinions[agent_name]
            elif hasattr(last_round, "round_2_opinions") and agent_name in last_round.round_2_opinions:
                opinion = last_round.round_2_opinions[agent_name]
            elif hasattr(last_round, "round_1_opinions") and agent_name in last_round.round_1_opinions:
                opinion = last_round.round_1_opinions[agent_name]
                
            if opinion and getattr(opinion, "standards_flags", None):
                for flag in opinion.standards_flags:
                    passed_str = "Passed" if flag.get("passed") else "Failed"
                    all_flags.append(
                        f"- **{agent_name.capitalize()}**: {flag.get('standard_name', 'Standard')} "
                        f"- {passed_str} ({flag.get('proposal_value', '')} vs threshold {flag.get('threshold', '')})"
                    )
        
        if all_flags:
            flags_text = "\n\n**Standards & Compliance Flags**\n" + "\n".join(all_flags)

    fallback_md = (
        "**[DETERMINISTIC FALLBACK]** *This brief was generated using verified deterministic calculations "
        "because live AI generation is currently unavailable (budget exhausted).*\\n\\n"
        f"**Resolution Outcome**\\n{summary['outcome']}\\n\\n"
        f"**Parameter Adjustments**\\n{summary['changes']}\\n\\n"
        "**Agent Perspectives**\\n"
        f"- {summary['finance_score']}\\n"
        f"- {summary['climate_score']}\\n"
        f"- {summary['community_score']}"
        f"{flags_text}"
    )
    return fallback_md


def generate_judge_brief(session: CourtroomSession) -> str:
    """Generate a narrative summary of the debate using Gemini.

    Parameters
    ----------
    session : CourtroomSession
        The courtroom session containing the full debate history.

    Returns
    -------
    str
        The narrative summary generated by Gemini.
    """
    history = build_audit_from_session(session)
    final_proposal = session.current_proposal

    if is_budget_exhausted():
        logger.warning("Skipping judge brief generation due to exhausted daily budget.")
        return generate_judge_brief_fallback(session)

    try:
        provider = get_provider()
        # Construct the prompt
        prompt = (
            "You are an executive summarizer for the 'Neighborhood Courtroom' AI simulation.\n"
            "Below is the raw audit history of a multi-agent debate regarding urban planning parameters.\n"
            "Please read the history and generate a concise, professional 'Judge Brief' (1-2 paragraphs).\n"
            "Focus on the main conflicts, which agents disagreed, and how the judge resolved them.\n"
            "Do not invent data; only summarize the provided history.\n\n"
            "## Final Proposal State\n"
            f"Housing Units: {final_proposal.housing_units}\n"
            f"Green Space: {final_proposal.green_space_pct}%\n"
            f"Parking Spaces: {final_proposal.parking_spaces}\n"
            f"Community Center Sqft: {final_proposal.community_center_sqft}\n\n"
            "## Audit History\n"
        )
        
        # We will dump all explain_parameter views into the prompt
        for param in ["housing_units", "green_space_pct", "parking_spaces", "community_center_sqft"]:
            explanation = history.explain_parameter(param)
            if "Unresolved or unknown" not in explanation:
                prompt += f"### Parameter: {param}\n{explanation}\n\n"
        
        return provider.generate_text(
            system_instruction="You are an executive summarizer for the 'Neighborhood Courtroom' AI simulation.",
            user_prompt=prompt
        )
    except Exception as e:
        logger.error(f"LLM API generation failed: {e}")
        return generate_judge_brief_fallback(session)
